---
# vars file for packages

# Detected OS
my_os: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

# Templates Copy
vsftpd_templates_copy: "{{ _vsftpd_templates_copy['all']
  | union ( _vsftpd_templates_copy[my_os]
  | default([]) ) }}"

# Services Enable
vsftpd_services_enable: "{{ _vsftpd_services_enable['all']
  | union ( _vsftpd_services_enable[my_os]
  | default([]) ) }}"

# SELinux Enable
vsftpd_selinux_enable: "{{ _vsftpd_selinux_enable['all']
  | union ( _vsftpd_selinux_enable[my_os]
  | default([]) ) }}"

# Packages lists
vsftpd_packages_install: "{{ _vsftpd_packages_install['all']
  | union ( _vsftpd_packages_install[my_os]
  | default([]) ) }}"
