---
# Configuration templates to copy
_vsftpd_templates_copy:
  all: []
  CentOS_7:
    - src: vsftpd.conf
      dest: /etc/vsftpd/vsftpd.conf
  RedHat_7:
    - src: vsftpd.conf
      dest: /etc/vsftpd/vsftpd.conf
  CentOS_8:
    - src: vsftpd.conf
      dest: /etc/vsftpd/vsftpd.conf
  RedHat_8:
    - src: vsftpd.conf
      dest: /etc/vsftpd/vsftpd.conf
  Fedora_31:
    - src: vsftpd.conf
      dest: /etc/vsftpd/vsftpd.conf
  Debian_10:
    - src: vsftpd.conf
      dest: /etc/vsftpd.conf
  Ubuntu_18:
    - src: vsftpd.conf
      dest: /etc/vsftpd.conf
