subscription: 
  rhel_development_teams: 2c94f6188e80762a018e8704c4ac0d60
  rhel_smart_management_std: 8a82c68d80862c7301808ba1de7157fe
graphical_interface: false
subscription_name: "rhel_development_teams"
