---
- name: add user to newly provisioned server
  tasks:

  - name: add mbredeme username
    ansible.builtin.user:
      name: "{{ portal_username }}"
      groups: wheel
      append: yes
      password: "{{ portal_password | password_hash('sha512') }}"
      update_password: always