---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
# vars: defaults in group_vars/all/aws_vars.yml
  vars:
    region: {{ default('us-east-1') }}

  tasks:
    - name: create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: ansible-ssa-demo_{{region}}
        cidr_block: 10.10.0.0/16
        region: "{{ region }}"
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: dedicated

    
    - name: attach internet gateway to vpc_subnet_id

    - name: add route table (add 0.0.0.0/0 target internet gateway ID)

    - name: create a subnet associated with vpc_subnet_id






