---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
#  vars:
#    defaults in group_vars/all/aws_vars.yml

#  collections: 
#    - amazon.aws

  tasks:
    - name: Provision Windows ec2 instance in AWS
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: started
        key_name: "{{ ssh_key_name }}"
        security_group: "{{ security_group_id }}"
        instance_type: "{{ instance_size }}"
        tags: 
          Env: "{{ env_tag }}"
          App: "{{ app_tag }}"
          Name: "{{ name_tag }}"
        image_id: "{{ ami_id[image_name] }}"
        wait: true
        vpc_subnet_id: "{{ subnet_id }}"
        count: "{{ instance_count }}"
        network:
          assign_public_ip: yes
        user_data: | 
          <powershell>
          $admin = [adsi]("WinNT://./administrator, user")
          $admin.PSBase.Invoke("SetPassword", "myTempPassword123!")
          Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
          </powershell>
      register: ec2_instance_facts_win
      when: image_name == "windows2019"

    - name: Provision RHEL ec2 instance in AWS
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: started
        key_name: "{{ ssh_key_name }}"
        security_group: "{{ security_group_id }}"
        instance_type: "{{ instance_size }}"
        tags: 
          Env: "{{ env_tag }}"
          App: "{{ app_tag }}"
          Name: "{{ name_tag }}"
        image_id: "{{ ami_id[image_name] }}"
        wait: true
        vpc_subnet_id: "{{ subnet_id }}"
        count: "{{ instance_count }}"
        network:
          assign_public_ip: yes
      register: ec2_instance_facts_rhel      
      when: image_name is match("rhel*")

    - name: show ec2_instance_facts information
      debug:  
        var: ec2_instance_facts

    - name: initialize target_hosts as an empty list
      set_fact:
        target_hosts: []

    - name: load new instances into target_hosts list (used in future plays for config)
      when: image_name is match("rhel*")
      set_stats:
        data: 
          target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
      loop: "{{ ec2_instance_facts_rhel.instances }}"

    - name: load new instances into target_hosts list (used in future plays for config)
      when: image_name == "windows2019" 
      set_stats:
        data: 
          target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
      loop: "{{ ec2_instance_facts_win.instances }}"

    - name: give instance time to initialize before configuration
      ansible.builtin.wait_for: 
        timeout: 150

#    - name: wait until provisioned instances are in "running" status
#      amazon.aws.ec2_instance_info: 
#      register: r_instance_facts
#      until: r_instance_facts.instances.state.name = "running"
#      retries: 30
#      delay: 10

#    - name: Wait 600 seconds for target connection to become reachable/usable
#      wait_for_connection:

#    - name: Wait for system to receive commands
#      delegate_to: "{{ item }}"
#      command: id 
#      register: result
#      until: result.rc = 0
#      retries: 35
#      delay: 10
#      loop: "{{ target_hosts }}"



