---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
# vars: defaults in group_vars/all/aws_vars.yml
  vars:
    aws_region: us-east-2
    vpc_number: 3

  tasks:

    # - name: get vpc info
    #   amazon.aws.ec2_vpc_net_info:
    #     region: "{{ region }}"
    #   register: r_vpc_info

    # - name: make sure a vpc with this name doesn't exist
    #   fail:
    #     msg: This VPC already exists
    #   when: ansible-ssa-demo-vpc{{vpc_number}} == item.vpcs.tags.Name
    #   loop: "{{ r_vpc_info.vpcs | subelements('tags') }}"
    #   loop: query( r_vpc_info.vpcs | wantlist=true

    - name: create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: ansible-ssa-demo-vpc{{vpc_number}}
        cidr_block: 10.0.{{vpc_number}}.0/24
        region: "{{ aws_region }}"
        tags:
          Name: ansible-ssa-demo-vpc{{vpc_number}}
        tenancy: default
      register: r_vpc_facts

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ r_vpc_facts.vpc.id }}"
        state: present
        region: "{{ aws_region }}"
        tags: 
          Name: ansible-ssa-demo-vpc{{ vpc_number }}-igw
      register: r_igw

    - name: Create subnet for servers
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ r_vpc_facts.vpc.id }}"
        cidr: 10.0.{{vpc_number}}.0/24
        region: "{{ aws_region }}"
        tags: 
          Name: ansible-ssa-demo-vpc{{ vpc_number }}-subnet
      register: r_subnet
    
    - name: Create gateway route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ r_vpc_facts.vpc.id }}"
        tags:
          Name: ansible-ssa-demo-vpc{{ vpc_number }}-rt
        subnets:
          - "{{ r_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ r_igw.gateway_id }}"
      register: r_gateway_route_table

    - name: Create Security group
      amazon.aws.ec2_group:
        name: ansible-ssa-demo-vpc{{vpc_number}}-sg
        description: sg with rule descriptions
        vpc_id: "{{ r_vpc_facts.vpc.id }}"
        # profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 443
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 443
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
          - proto: tcp
            ports:
            - 27199
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 27199
          - proto: tcp
            ports:
            - 5432
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 5432
      register: r_sg


#    - name: attach internet gateway to vpc_subnet_id

#    - name: add route table (add 0.0.0.0/0 target internet gateway ID)

#    - name: create a subnet associated with vpc_subnet_id






