---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
  vars:
    security_group_id: sg-079ebd58a00104d74
    ami_id: ami-06f1e6f8b3457ae7c
    instance_size: m4.xlarge
    instance_tags: {'Name':'mkb-platform-ec2-instance'}
    vpc_id: vpc-0b41ab809d8ee56f6
    ssh_key_name: aws-rhpds-20211028
    region: us-east-2
    subnet_id: subnet-0f2f38197f3ed1263
    instance_count: 1


  collections: 
    - amazon.aws

  tasks:

  - name: Provision instance
    amazon.aws.ec2_instance:
      region: "{{ region }}"
      state: started
      key_name: "{{ ssh_key_name }}"
      security_group: "{{ security_group_id }}"
      instance_type: "{{ instance_size }}"
      tags: "{{ instance_tags }}"
      image_id: "{{ ami_id }}"
      wait: true
      #wait_timeout: 120
      vpc_subnet_id: "{{ subnet_id }}"
      count: "{{ instance_count }}"
      network:
        assign_public_ip: yes
    register: ec2_instance_facts

  - name: show ec2_facts
    debug:
      var: ec2_instance_facts 
      #var: ec2_instance_facts.instances[0].public_dns_name

  - name: show ec2_facts
    debug:
      var: ec2_instance_facts | type_debug
      #var: ec2_instance_facts.instances[0].public_dns_name

  - name: show ec2_facts
    debug:
      var: ec2_instance_facts.instance_ids | type_debug
      #var: ec2_instance_facts.instances[0].public_dns_name

  - name: 
    amazon.aws.ec2_instance_info:
      region: "{{ region }}"
      instance_ids:
        - "{{ ec2_instance_facts.instance_ids[0] }}"
    register: ec2_instance_facts_detailed

  - name: show ec2_facts
    debug:
      var: ec2_instance_facts_detailed
      #var: ec2_instance_facts.instances[0].public_dns_name

  - name: 
    ansible.builtin.add_host:
      name: "{{ ec2_instance_facts.instances[0].private_dns_name }}"
      groups: NewInsightInstance

#  - name:
#    ansible.builtin.set_stats:
#      data: 
#        target_hosts: "{{ ec2_instance_facts.instances[0].public_dns_name }}"
  
  - name: initialized target_hosts
    set_fact:
      target_hosts: []

  - name: is list transfered without indexing through
    set_stats:
      data: 
        target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
    loop: "{{ ec2_instance_facts.instances }}"

  - name: is target_hosts a list
    debug:  
      var: target_hosts

  - name:
    ansible.builtin.set_stats:
      data: 
        wf_ec2_instance_facts: "{{ ec2_instance_facts }}"


  - name: give instance time to initialize
    ansible.builtin.wait_for: 
      timeout: 120
