---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
  vars:
    security_group_id: sg-079ebd58a00104d74
    ami_id:
      rhel84: ami-0635a8c4049019474
      rhel85: ami-06f1e6f8b3457ae7c
    instance_size: m4.xlarge
    vpc_id: vpc-0b41ab809d8ee56f6
    ssh_key_name: aws-rhpds-20211028
    region: us-east-2
    subnet_id: subnet-0f2f38197f3ed1263
    instance_count: 1

  collections: 
    - amazon.aws

  tasks:
    - name: Provision instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: started
        key_name: "{{ ssh_key_name }}"
        security_group: "{{ security_group_id }}"
        instance_type: "{{ instance_size }}"
        tags: 
          Env: "{{ env_tag }}"
          App: "{{ app_tag }}"
          Name: "{{ name_tag }}"
        image_id: "{{ ami_id[image_name] }}"
        wait: true
        vpc_subnet_id: "{{ subnet_id }}"
        count: "{{ instance_count }}"
        network:
          assign_public_ip: yes
      register: ec2_instance_facts

    - name: initialize target_hosts as an empty list
      set_fact:
        target_hosts: []

    - name: load target_hosts list with hosts to target for configuration
      set_stats:
        data: 
          target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
      loop: "{{ ec2_instance_facts.instances }}"

    - name: show me running instances
      debug:  
        var: item.public_dns_name
      loop: "{{ ec2_instance_facts.instances }}"




#    - name: give instance time to initialize
#      ansible.builtin.wait_for: 
#        timeout: 120
