---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: all
  #test
  tasks:
  - name: Disable rhui repositories
    ansible.builtin.shell: yum-config-manager --disable *rhui*

  - name: register system and attach smart management subscription
    community.general.redhat_subscription:
      state: present
      username: mbredeme
      password: Toonces1!
      pool_ids: 8a85f9a178a823b20178ccaf437d272c
      # consider using activation key parameter instead (see examples in docs)

#  - name: configure system to use CDN by default (preven reset to rhui on reboot)
#    ansible.builtin.shell: "subscription-manager --rhsm.manage_repos=1"

  - name: Enable Ansible 2.9 rhsm repository in redehat.repo file
    community.general.rhsm_repository:
      name: ansible-2.9-for-rhel-8-x86_64-rpms
      state: enabled

#  - name: Add Ansible Engine repositories
#    ansible.builtin.yum_repository: 
#      name: ansible-2.9-for-rhel-8-x86_64-rpms
#      baseurl: https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.9/os
#      description: "Red Hat Ansible Engine 2.9 for RHEL 8 x86_64 (RPMs)"
#      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
#      gpgcheck: yes
#      enabled: yes

  - name: install ansible Engine
    ansible.builtin.yum:
      name: ansible
      state: present

  - name: install rhc playbook
    ansible.builtin.yum:
      name: rhc-worker-playbook
      state: present

  - name: update to current release 
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: register insights client
    insights_register:
      state: present
