---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: all

  tasks:

  - name: Disable rhui repositories
    ansible.builtin.shell: yum-config-manager --disable *rhui*

  - name: wipe out subscription status from ansible.builtin.command
    ansible.builtin.shell: subscription-manager clean

  - name: register system and attach smart management subscription
    community.general.redhat_subscription:
      state: present
      username: "{{ portal_username }}"
      password: "{{ portal_password }}"
      force_register: yes
      pool_ids: 8a85f9a178a823b20178ccaf437d272c
      # consider using activation key parameter instead (see examples in docs)

  - name: enable subscription manager
    ansible.builtin.shell: subscription-manager config --rhsm.manage_repos=1

  - name: Enable Ansible 2.9 rhsm repository in redehat.repo file
    community.general.rhsm_repository:
      name: ansible-2.9-for-rhel-8-x86_64-rpms
      state: enabled

  - name: install ansible Engine
    ansible.builtin.yum:
      name: ansible
      state: present

  - name: install rhc playbook
    ansible.builtin.yum:
      name: rhc-worker-playbook
      state: present

  - name: install red hat connector
    ansible.builtin.yum:
      name: rhc
      state: present

  - name: run Red Hat Connector
    ansible.builtin.command: rhc connect -u {{ portal_username }} -p {{ portal_password }}

  - name: give insights time to finish setup after running RHC
    ansible.builtin.wait_for: 
      timeout: 60

  - name: update insights data
    ansible.builtin.command: insights-client
    ignore_errors: yes

  - name: install webconsole aka cockpit
    ansible.builtin.yum:
      name: cockpit
      state: latest

  - name: start cockpit socket
    ansible.builtin.service: 
      name: cockpit.socket
      enabled: yes
      state: started

  - name: add {{ portal_username }} user
    ansible.builtin.user:
      name: "{{ portal_username }}"
      groups: wheel
      append: yes
      password: "{{ portal_password | password_hash('sha512') }}"
      update_password: always