---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: all
  #test
  tasks:
  - name: Disable rhui repositories
    ansible.builtin.command: yum-config-manager --disable *rhui*

#  - name: register system and attach smart management subscription
#    community.general.redhat_subscription:
#      state: present
#      username: mbredeme
#      password: Toonces1!
#      pool_ids: 8a85f9a178a823b20178ccaf437d272c
      # consider using activation key parameter instead (see examples in docs)

  - name: configure system to use CDN by default (preven reset to rhui on reboot)
    ansible.builtin.command: subscription-manager --rhsm.manage_repos=1

  - name: Add Ansible Engine repositories
    ansible.builtin.yum_repository: 
      name: ansible-2.9-for-rhel-8-x86_64-rpms
      state: present

  - name: install ansible Engine
    yum:
      name: ansible
      state: present

  - name: install rhc playbook
    yum:
      name: rhc-worker-playbook
      state: present