---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: "{{ target_hosts }}"
  ignore_errors: true
  vars:
    subscription: 
      rhel_development_teams: 2c946cd0887328c30188a02782cf3b9e
      rhel_smart_management_std: 2c946cd0887328c30188a02722753b90

  roles: 
    - configure_base_instance
