---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: "{{ target_hosts }}"

  tasks:
    - name: Wait for system to receive commands
      command: id 
      register: result
      until: result.stdout.find("all systems go") != -1
      retries: 35
      delay: 10