---
- name: just messing around
  hosts: localhost
  vars: 
    some_value: 
      - 4
      - 2
      - 3
      - 8
    other_value:
      - a
      - b
      - c
    third_value:
      - '*'
      - '#'
      - '+'

  tasks:
  - debug: 
      msg: "{{ some_value }}, {{ other_value}}, and {{ third_value}} flattened is {{ [some_value, other_value, third_value] | flatten(other_value) }}"