---
- name: just messing around
  hosts: localhost
  vars: 
    some_value: 
      - 4
      - 2
      - 3
      - 8

  tasks:
  - debug: 
      msg: "{{ some_value }} sorted is  {{ some_value | sort }}"