---
- name: just messing around
  hosts: localhost
  vars: 
    some_value: 
      - 4
      - 2
      - 8
    other_value:
      - 4
      - 3
      - 9
    third_value:
      - '*'
      - '#'
      - '+'

  tasks:
  - debug: 
      msg: difference between {{ some_value }} and {{ other_value}} is {{ some_value | difference(other_value) }}"