---
- name: just messing around
  hosts: localhost
  vars: 
    some_dictionary: 
      key1: value1
      key2: value2
      key3: value3
    other_dictionary:
      key1: value1
      key2: value is different
      key3: value3
      keyA: ValueA

  tasks:
  - debug: 
      msg: Dictionary {{ some_dictionary }} converted to list is {{ some_dictionary | dict2items }}