---
- name: just messing around
  hosts: localhost
  vars: 
    some_dictionary: 
      key1: value1
      key2: value2
      key3: value3
    other_dictionary:
      key1: value1
      key2: value is different
      key3: value3
      keyA: ValueA

  tasks:
  - debug: 
      msg: Dictionaries {{ some_dictionary }} and {{ other_dictionary }} combined is {{ some_dictionary | combine(other_dictionary) }}