---
- name: just messing around
  hosts: all
  vars: 
    some_dictionary: 
      - key: k1
        value:  
          - A
          - B
          - C
      - key: k2
        value: 
          - D
          - E
    other_dictionary:
      key1: value1
      key2: value is different
      key3: value3
      keyA: ValueA

  tasks:
  - debug: 
      msg: Items {{ some_dictionary }} converted to dictionary is {{ some_dictionary | items2dict }}