---
- name: just messing around
  hosts: localhost
  vars: 
    some_dictionary: 
      k1: 
        - A
        - B
        - C
      k2: 
        - D
        - E
    other_dictionary:
      key1: value1
      key2: value is different
      key3: value3
      keyA: ValueA

  tasks:
  - debug: 
      msg: Dictionary {{ some_dictionary }} converted to list is {{ some_dictionary | dict2items }}