---
- name: install aap from backup
  hosts: aap_demo_controller
  vars: 
    installer_url: 'https://access.cdn.redhat.com/content/origin/files/sha256/eb/eb4573d15785d441782279ac7404d763e3905e7032f38d8bfa40bc75c68f9ea1/ansible-automation-platform-setup-2.4-2.tar.gz?user=145a9a523e663ed1033cd6d7d781ba2c&_auth_=1698933853_3ceab3231e72a275cb050231312df18d'
    backup_tar_url: 'https://www.dropbox.com/scl/fi/x2ai7dzbtkclowvjoqt6x/ac_backup2023-10-25_version_2.4-1.tar.gz?rlkey=ao33mgq52aaszo6gqtk5wj39r&dl=0'
    aap_version: '2-4'
    rhel_os: "rhel_8"
    bundle: "not_bundled" # options "bundled" or "not_bundled"
    install_dir: /root

  tasks:
    - name: Ensure install directory exists
      ansible.builtin.file:
        path: "{{install_dir}}/install-{{aap_version}}-{{bundle}}"
        state: directory

#    - name: download and extract installer file from CDN
#      block: 
#        - name: download tar - CDN
#          get_url:
#            url: "{{installer_url}}"
#            dest: "/root"
#          register: tar_from_cdn
#
#        - name: extract installation tar file
#          command: tar -xzf {{tar_from_cdn.dest}} --strip-components=1 -C /root/install_aap_{{aap_version}}/
#          register: extraction_result
#    
#      when: "'access.cdn.redhat' in installer_url"

    - name: download and exxtract Installer from dropbox
      block:
        - name: download tar dropbox
          ansible.builtin.shell: >
            curl -o installer-{{aap_version}}-{{bundle}}.tar.gz   -X POST https://content.dropboxapi.com/2/files/download   
            --header "Authorization: Bearer {{access_token}}"   
            --header "Dropbox-API-Arg: {\"path\":\"/Apps/Automation_Controller/{{backup_file_name}}\"}"
          args:
            chdir: "{{install_dir}}"
          register: tar_from_dropbox

        - name: extract installation tar file
          command: tar -xzf installer-{{aap_version}}-{{bundle}}.tar.gz --strip-components=1 -C /root/install_aap_{{aap_version}}/
          register: extraction_result

      when: "'dropbox' in installer_url"

    - name: Add templates file to installation directory
      template:
        src: inventory{{aap_version}}.j2
        dest: "{{install_dir}}/install-{{aap_version}}-{{bundle}}/inventory"

#    - name: Fetch HTML page
#      ansible.builtin.uri:
#        url: http://ec2-23-20-120-44.compute-1.amazonaws.com/
#      register: html_response
#
#    - name: HTML Status
#      debug:
#        var: html_response

    - name: Run setup.sh script
      ansible.builtin.shell: ./setup.sh
      args:
        chdir: "{{install_dir}}/install-{{aap_version}}-{{bundle}}"

    - name: backup isntallation version to dropbox (needed for future restores)
      ansible.builtin.shell: >
        curl -X POST https://content.dropboxapi.com/2/files/upload 
        --header "Authorization: Bearer {{ access_token }}"
        --header "Dropbox-API-Arg: {\"path\": \"/Apps/Automation_Controller/{{tar.dest}}\",\"mode\": \"overwrite\",\"autorename\": true,\"mute\": false}" 
        --header "Content-Type: application/octet-stream" 
        --data-binary @{{tar.dest}}
      args:
        chdir: "{{ install_dir }}"
      tags: download


#    - name: download backup file
#      get_url:
#        url: "{{backup_tar_url}}"
#        dest: "/root/install_aap_{{aap_version}}/"