---
- name: install aap from backup
  hosts: _aap_demo_controller
  vars: 
    backup_tar_url: 'https://www.dropbox.com/scl/fi/x2ai7dzbtkclowvjoqt6x/ac_backup2023-10-25_version_2.4-1.tar.gz?rlkey=ao33mgq52aaszo6gqtk5wj39r&dl=0'
    installer_url: https://access.cdn.redhat.com/content/origin/files/sha256/eb/eb4573d15785d441782279ac7404d763e3905e7032f38d8bfa40bc75c68f9ea1/ansible-automation-platform-setup-2.4-2.tar.gz?user=145a9a523e663ed1033cd6d7d781ba2c&_auth_=1698871603_96795007652d5fe2bf3e9c38c5a118ee
    aap_version: '2.4-1'
    rhel_os: "8.8"
    bundle: False

  tasks:
    - name: download installation tar file
      get_url:
        url: "{{installer_url}}"
        dest: "/root"
      register: results

    - name: show results
      debug:
        var: results

#    - name: download backup file
#      get_url:
#        url: "{{backup_tar_url}}"
#        dest: "/root"