---
- name: Pinging hosts
  hosts: "{{ target_host }}"

  tasks:
    - name: what is the hostname
      debug:
        var: inventory_hostname

    - name: ping hosts
      ping:

    - name: show text area data
      debug:
        var: text_box_stuff