---
- name: refresh automation hub token so it doesn't expire
  hosts: localhost

  tasks:
    - command: curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id="cloud-services" -d refresh_token="***REMOVED***" --fail --silent --show-error --output /dev/null