# customer considerations:
#   where will private keys be stored 
#     - /home/<user>/.ssh on bastion?
#     - key storage service?
#     - this demo assumes /home/<user>/.ssh
#   define users: who needs new keys
#   define targets: what systems need the public keys
# modules:
#   - https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
#     This module allows one to (re)generate OpenSSH private and public keys. It uses ssh-keygen to generate keys.
# demo specific:
#   provision 4 servers:
#     - bastion
#     - server1
#     - server2
#     - server3
---
- name: rotatate ssh key demo
  hosts: local_host, Name_bastion 
  vars:
    users:
      - usera
      - userb
      - userc

  roles: 
    - role: create_users
    - role: generate_new_ssh_keys

- name: play2
  hosts: local_host, Name_server*
  
  roles:
    - role: distribute_public_keys
