---
- name: shutdown Dev aws instances
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: us-east-1

  tasks:
    - name: gather running instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        uptime: 1
        filters:
          "tag:env": "Dev"
          instance-state-name: [ "running" ]
      register: ec2_instance_facts

    - debug:  
        msg: "{{ item.public_dns_name }}"
      loop: "{{ ec2_instance_facts.instances }}"

    - name: shut down instances
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids: "{{ item.instance_id }}"
        state: stopped
      loop: "{{ ec2_instance_facts.instances }}"
