---
- name: determine running aws instances
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: us-east-1

  tasks:
    - name: gather instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        uptime: 60
        filters:
          #"tag:Env": "Dev"
          instance-state-name: [ "running"]
      register: ec2_instance_facts

    - name: initialize target_hosts as an empty list
      set_fact:
        target_hosts: []

    - name: load target_hosts list with hosts to target for configuration
      set_stats:
        data: 
          target_hosts: "{{ target_hosts + [ item.public_dns_name ] }}"
      loop: "{{ ec2_instance_facts.instances }}"

    - name: shows running instances
      debug:  
        msg: Here are the target hosts {{ target_hosts }}

- name: shut down running instances
  hosts: target_hosts