- name: initial setup of groups for insights
  hosts: "{{ group_value }}"  # provided in JT survey (must match an aws group)

  tasks:
  - name: ensure tags.yml exists
    file:
      state: touch
      dest: /etc/insights-client/tags.yaml

  - name: add group {{ target_group }} to be used in insights
    lineinfile: 
      line: "{{group_key}}: {{ group_value }}"
      regexp: "^{{group_key}}}"
      path: /etc/insights-client/tags.yaml
      group: root
      owner: root
      mode: 0644
    ignore_errors: yes

  - name: refresh insights data
    command: insights-client


