- include_tasks: rhel_config.yml
  when: '"rhel8" in image_name'

- include_tasks: windows_config.yml
  when: image_name == "windows2019"

- include_tasks: windows_config.yml
  when: '"fedora" in image_name'

- include_tasks: graphical_interface.yml
  when: (graphical_interface == false)  and ('"rhel8" in image_name')