- include_tasks: rhel_config.yml
  when: '"rhel" in image_name'

- include_tasks: windows_config.yml
  when: image_name == "Windows2019"

- include_tasks: windows_config.yml
  when: '"fedora" in image_name'

- include_tasks: graphical_interface.yml
  when: (graphical_interface == true)  and ('"rhel8" in image_name')