---
ami_id:
  us-east-1:
    rhel86: ami-03debf3ebf61b20cd
    rhel88: ami-046981daef262e1d8
    rhel92: ami-093e0758ef99ec8a4
    windows2019: ami-04b707657b5bf6b20 # EC2LaunchV2-Windows_Server-2019-English-Full-Base-2023.06.14
    fedora36: ami-0e8125571ebaa4000
  us-east-2:
    rhel86: ami-0251f146af87abba4
    rhel92: ami-0c5cbb3977cbe4a24
    windows2019: ami-017ab573701202ba1
    fedora36: ami-00a5a17c57aea0e46
  us-west-1:
    rhel86: ami-0761d0d4bf33910e9
    windows2019: 
    fedora36:    
instance_size: m4.xlarge
# ssh_key_name: ansible-ssa-demo-key-20230621
instance_tags: {'Name':'mkb-platform-ec2-insights-demo'}
boto_profile: "3.3"
aws_vpcs:
  vpc3:
    aws_subnet_id: subnet-0df9348ab8545bb7e
    aws_vpc_id: vpc-0a56e4ed93831f4ac
    aws_security_group_id: sg-0eb817e60557f4186
    aws_region: us-west-1
  vpc2: 
    aws_subnet_id: "subnet-007eedf03dee6b9f0"
    aws_vpc_id: vpc-0d1f472b83a0ab389
    aws_security_group_id: sg-09bdf99e647385e98
    aws_region: us-east-2
  vpc1: 
    aws_subnet_id: "subnet-06bc0f34295e7e157"
    aws_vpc_id: vpc-007828154553ad014
    aws_security_group_id: sg-0b3653950c650412b
    aws_region: us-east-1
graphical_interface: false
  # vpc1b: 
  #   aws_subnet_id: subnet-053dc4cfd35c4b869
  #   aws_vpc_id: vpc-09654defecfdfffa1
  #   aws_security_group_id: sg-07132b7655c4910cc
  #   aws_region: us-east-1
_image_id_: ami-08b207be5fdce406f
_region_: us-east-1
vpc_name: "{{ vpc_prefex}} VPC"
_vpc_cidr_block_: '12.0.0.0/16'
igw_name: "{{ vpc_prefex}} IGW"
_subnet_cidr_: '12.0.1.0/24'
subnet_name: "{{ vpc_prefex}} Subnet"
_route_table_name_: "{{ vpc_prefex}} Route Table"
destination_cidr_block: '0.0.0.0/0'
_security_group_: "{{ vpc_prefex}}SG"
_key_name_: "{{ vpc_prefex}}key"
_instance_type_: "t2.micro"