---
security_group_id: sg-0bdbd70e35827b5f9
ami_id:
  us-east-1:
    rhel84: ami-0635a8c4049019474
    rhel85: ami-06f1e6f8b3457ae7c
    rhel86: ami-03debf3ebf61b20cd
    windows2019: ami-041306c411c38a789
  us-east-2:
    rhel85: ami-009ed7fcb93e10f3a
    rhel86: ami-0251f146af87abba4
    windows2019: ami-017ab573701202ba1
instance_size: m4.xlarge
instance_tags: {'Name':'mkb-platform-ec2-insights-demo'}
vpc_id: vpc-0c905f1fdf60945bd
ssh_key_name: ansible-ssa-demo-key
region: us-east-1
subnet_id: subnet-0cd4ed414d34e70e5
boto_profile: "3.3"
aws_vpcs:
  vpc3:
    subnet_id: "subnet-0aa1c2efd61231bbf"
    vpc_id: vpc-0a603597a0a38f1dd
  vpc2: 
    subnet_id: "subnet-0cd4ed414d34e70e5"
    vpc_id: vpc-0c905f1fdf60945bd