---
ami_id:
  us-east-1:
    rhel84: ami-0635a8c4049019474
    rhel85: ami-06f1e6f8b3457ae7c
    rhel86: ami-03debf3ebf61b20cd
    windows2019: ami-09893189de3a034b4
    fedora36: ami-0e8125571ebaa4000
  us-east-2:
    rhel84: ami-091e34016fb73b952
    rhel85: ami-009ed7fcb93e10f3a
    rhel86: ami-0251f146af87abba4
    windows2019: ami-017ab573701202ba1
    fedora36: ami-00a5a17c57aea0e46
instance_size: m4.xlarge
ssh_key_name: ansible-ssa-demo-key-20220104
instance_tags: {'Name':'mkb-platform-ec2-insights-demo'}
boto_profile: "3.3"
aws_vpcs:
  vpc3:
    aws_subnet_id: "subnet-0aa1c2efd61231bbf"
    aws_vpc_id: vpc-0a56e4ed93831f4ac
    aws_security_group_id: sg-0eb817e60557f4186
    aws_region: us-west-1
  vpc2: 
    aws_subnet_id: "subnet-0df9348ab8545bb7e"
    aws_vpc_id: vpc-0200f8c07e25f0f38
    aws_security_group_id: sg-03ff555569c77d8f1
    aws_region: us-east-2
  # vpc1: 
  #   aws_subnet_id: subnet-004f779fd14ec43fd
  #   aws_vpc_id: vpc-0c090f1f2c42ff279
  #   aws_security_group_id: sg-07132b7655c4910cc
  #   aws_region: us-east-1
  # vpc1b: 
  #   aws_subnet_id: subnet-053dc4cfd35c4b869
  #   aws_vpc_id: vpc-09654defecfdfffa1
  #   aws_security_group_id: sg-07132b7655c4910cc
  #   aws_region: us-east-1