- name: create users for demo purposes
  user: 
    name: "{{item}}"
    generate_ssh_key: true
  loop: "{{ users }}"
  register: r_new_user_data

- name: show user data
  debug: 
    var: r_new_user_data
