---
# tasks file for generate_new_ssh_keys
- name: Force regenerate an OpenSSH keypair if it already exists
  community.crypto.openssh_keypair:
    path: /home/{{item}}/id_rsa
    force: True
    comment: "{{item}}"
  loop: "{{users}}"
  register: r_new_keys

- name: initialize bastion_server variable
  set_fact:
    bastion_server: "{{inventory_hostname}}"

- name: is bastion server present  
  debug:
    var: ansible_facts

- name: load some_server with bastion host to use in subsequent plays
  set_stats:
    data: 
      some_server: ['ansible_facts']
    
- name: does bastion server work before the next play is run?
  debug:
    var: some_server
      
