---
# tasks file for generate_new_ssh_keys
- name: Force regenerate an OpenSSH keypair if it already exists
  community.crypto.openssh_keypair:
    path: /home/{{item}}/id_rsa
    force: True
    comment: "{{item}}"
  loop: "{{users}}"
  register: r_new_keys

- name: value of r_new_keys
  debug:
    var: r_new_keys

- name: add r_new_keys to global play vars
  set_stats:
    data: 
      new_key_data: r_new_keys.results
    per_host: yes
    
- name: new_key_data value
  debug:
    var: new_key_data

- name: refresh ansible gather_facts
  setup:
      
