---
# tasks file for generate_new_ssh_keys
- name: Force regenerate an OpenSSH keypair if it already exists
  community.crypto.openssh_keypair:
    path: /home/{{item}}/id_rsa
    force: True
    comment: "{{item}}"
  loop: "{{users}}"
  register: r_new_keys



- name: load target_hosts list with hosts to target for configuration
  set_stats:
    data: 
      bastion_server: "{{inventory_hostname}}"
    per_host: yes
    
    
- name: does bastion server work before the next play is run?
  debug:
    var: ansible_stats.data.bastion_server
      
