---
# tasks file for generate_new_ssh_keys
- name: Force regenerate an OpenSSH keypair if it already exists
  community.crypto.openssh_keypair:
    path: /home/{{item}}/id_rsa
    force: True
    comment: "{{item}}"
  loop: "{{users}}"
  register: r_new_keys

- name: initialize bastion_server variable
  set_fact:
    bastion_server: "{{inventory_hostname}}"

- name: load target_hosts list with hosts to target for configuration
  set_stats:
    data: 
      some_server: "{{bastion_server}}"
      
- name: what is the value of inventory_hostname    
  debug:
    var: inventory_hostname
    
- name: does bastion server work before the next play is run?
  debug:
    var: hostvars['localhost']some_server
      
