---
# tasks file for generate_new_ssh_keys
- name: Force regenerate an OpenSSH keypair if it already exists
  community.crypto.openssh_keypair:
    path: /home/{{item}}/id_rsa
    force: True
    comment: "{{item}}"
  loop: "{{users}}"
  register: r_new_keys

- name: value of r_new_keys
  debug:
    var: r_new_keys

- name: add r_new_keys to global play vars
  set_fact: 
    new_key_data: "{{r_new_keys.results}}"

#- set_fact: 
#    bastion_server: "{{ inventory_hostname }}"
#  delegate_to: localhost
  
#- debug:
#    var: hostvars['localhost']['ansible_facts']['bastion_server']
    
#- name: refresh ansible gather_facts
#  setup:


 
