---
# tasks file for distribute_public_keys

#- name: r_new_keys comment index 0
#  debug:
#    var: hostvars[bastion_server]['new_key_data'][0]['comment']

- name: loop trhough r_new_keys 
  debug:
    msg: | 
      Here comes a user: {{ item['comment'] }}
      Here is their pubkey: {{ item['public_key'] }}
  loop: "{{ hostvars[bastion_server]['new_key_data'] }}"
  when: inventory_hostname != bastion_server

- name: ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{item.comment}}/.ssh
    state: directory
    mode: '0700'
  loop: "{{hostvars[bastion_server]['new_key_data']}}"
  when: inventory_hostname != bastion_server

- name: ensure authorized_keys exists
  ansible.builtin.file:
    path: /home/{{item.comment}}/.ssh/authorized_keys
    state: file
    mode: '0644'
  loop: "{{hostvars[bastion_server]['new_key_data']}}"
  when: inventory_hostname != bastion_server

- name: add authorized_key
  lineinfile:
    path: "/home/{{item.comment}}/.ssh/authorized_keys"
    regexp: '^ssh-rsa'
    line: "{{ item['public_key'] }}"
    owner: "{{item.comment}}"
    group: "{{item.comment}}"
    mode: '0644'
  loop: "{{hostvars[bastion_server]['new_key_data']}}"
  when: inventory_hostname != bastion_server
  
#- name: update authorized keys file 
#  authorized_key:
#    user: "{{ item['comment'] }}"
#    state: present
#    key: "{{ item['public_key'] }}"
#  loop: "{{ hostvars[bastion_server]['new_key_data']}}"
#  when: inventory_hostname != bastion_server

# name: show key data
# debug:
#   var: "{{hostvars[bastion_server]['r_new_keys'][0]['comment']}}'s pub key is: {{hostvars[bastion_server][0]['r_new_keys']['comment']}}"
##  loop: "{{hostvars[bastion_server]['r_new_keys']}}"

- name: r_new_keys as defined by bastion server sub attribute
  debug:
    var: bastion_server['new_key_data']

#- name: create a directory to store the file
#  file:
#    name: /tmp/"{{ item }}"
#    state: directory
#  loop: "{{users}}"

#- name: copy the local user ssh key to temporary {{ username }} key
#  shell: 'cat /home/{{ username }}/.ssh/id_rsa.pub > /tmp/{{ username }}/id_rsa.pub'

#- name: verify that file exists
#  command: ls -l {{ username }}/

#- name: setup remote host
#  hosts: bastion, server*
#  tasks:
#    - name: create remote user, no need for SSH key
#      user:
#        name: "{{ item }}"
#      loop: "{{users}}"

#    - name: use authorized_key to set the password
#      authorized_key:
#        user: "{{ username }}"
#        key: "{{ lookup('file', './'+ username +'/id_rsa.pub') }}"
